[[plugins]]
repo = 'Shougo/dein.vim'

# NERDTreeを設定
[[plugins]]
repo = 'scrooloose/nerdtree'

# devicons 利用
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

# インデント設定
[[plugins]]
repo = 'junegunn/vim-easy-align'

# カラースキーマ
[[plugins]]
repo = 'mrkn/mrkn256.vim'
hook_add = '''
colorscheme mrkn256
syntax enable
'''

# タグジャンプ用タグバー
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
nmap <F8> :TagbarToggle<CR>
'''

# ステータスライン
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
	let g:airline_theme = 'wombat'
	let g:airline_powerline_fonts = 1
'''
# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
" Vim
let g:indentLine_color_term = 239

" GVim
let g:indentLine_color_gui = '#A4E57E'

" none X terminal
let g:indentLine_color_tty_light = 7 " (default: 4)
let g:indentLine_color_dark = 1 " (default: 2)

" Background (Vim, GVim)
" let g:indentLine_bgcolor_term = 202
" let g:indentLine_bgcolor_gui = '#FF5F00'

let g:indentLine_char_list = ['|', '¦', '┆', '┊']
'''

# コード補完 coc
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = '''
" Use <C-l> スニペット候補表示
imap <C-l> coc-snippets-expand
" 構文エラーメッセージの表示待ち時間(ms)(default=4000)
set updatetime=300
'''

