# 編集中のMarkdownファイルのプレビューを作成する
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']
hook_add = """
let g:previm_open_cmd = 'open -a Google\ Chrome'
" ctrl pでプレビュー
nnoremap <silent> <C-p> :PrevimOpen<CR>
"""

# カッコやdef〜endの入力保管
[[plugins]]
repo = 'kana/vim-smartinput'
on_ft = ['ruby']

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# rails
[[plugins]]
repo = 'tpope/vim-rails'
