# カッコやdef〜endの入力保管
[[plugins]]
repo = 'kana/vim-smartinput'
on_ft = ['ruby']

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# rails
[[plugins]]
repo = 'tpope/vim-rails'

# Vdebug
[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["php", "javascript"]

# previm
[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
hook_add = """
let g:previm_open_cmd = 'open -a Google\ Chrome'
let g:previm_show_header = 0
" ctrl pでプレビュー
nnoremap <silent> <C-p> :PrevimOpen<CR>
"""
