# Maekdown編集
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']

# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# 編集中のMarkdownファイルのプレビューを作成する
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']

# プレビューをブラウザで開いてくれる
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']

# カッコやdef〜endの入力保管
[[plugins]]
repo = 'kana/vim-smartinput'
on_ft = ['ruby']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

# コードの自動補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 1
inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
'''

# vim8でdeopleteを使うのに必要
[[plugins]]
repo = 'roxma/nvim-yarp'

# vim8でdeopleteを使うのに必要
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# スニペット
# ruby
[[plugins]]
repo = 'fishbullet/deoplete-ruby'

# php
[[plugins]]
repo = 'lvht/phpcd.vim'
hook_add = '''
let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
let g:deoplete#ignore_sources.php = ['omni']
'''
